import assert from "node:assert/strict"
import { readFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const indexHtml = await readFile(path.join(rootDir, "frontend", "index.html"), "utf8")
const calculateJs = await readFile(path.join(rootDir, "frontend", "calculate.js"), "utf8")

assert.match(indexHtml, /id="driveDiscSchemeList"/, "Drive-disc workbench should expose one active scheme list.")
assert.match(indexHtml, /id="driveDiscSchemeTabs"/, "Drive-disc workbench should expose unified scheme tabs.")
assert.match(indexHtml, /id="optimizerResultTabs"/, "Optimizer result tabs should still exist as candidate tab items.")
assert.doesNotMatch(indexHtml, /id="discPicker"/, "Manual drive-disc selection should no longer use the old six-select picker.")
assert.doesNotMatch(indexHtml, /id="currentPlanList"/, "Current plan should not render as a separate list.")
assert.doesNotMatch(indexHtml, /id="optimizerResultList"/, "Optimizer results should not render as a separate list.")
assert.match(indexHtml, /id="damageTargetStunned"[^>]*checked/, "Boss stun multiplier should be enabled by default.")
assert.match(indexHtml, /class="field target-stun-field"[\s\S]*id="damageTargetStunned"[\s\S]*id="damageTargetStunMultiplier"/, "Boss stun toggle and multiplier should share one field.")
assert.doesNotMatch(indexHtml, /target-stun-multiplier-field/, "Boss stun multiplier should not render as a separate field.")
assert.match(indexHtml, /id="damageTargetResistanceLabel">物理抗性/, "Target resistance should default to the current agent element label.")
assert.match(indexHtml, /id="damageTargetResistance"[^>]*step="1"/, "Custom target resistance should step by whole percent.")
assert.match(indexHtml, /id="combatBuffModalSummary"/, "Combat Buff modal should show a pending selection summary.")
assert.match(indexHtml, /id="cancelCombatBuffModalBtn"/, "Combat Buff modal should expose an explicit cancel button.")
assert.match(indexHtml, /id="applyCombatBuffModalBtn"/, "Combat Buff modal should expose an explicit apply button.")
assert.match(indexHtml, /id="cancelTwoPieceSetModalBtn"/, "Two-piece limit modal should expose an explicit cancel button.")
assert.match(indexHtml, /id="applyTwoPieceSetModalBtn"/, "Two-piece limit modal should expose an explicit apply button.")
assert.match(indexHtml, /id="cancelFourPieceSetModalBtn"/, "Four-piece limit modal should expose an explicit cancel button.")
assert.match(indexHtml, /id="applyFourPieceSetModalBtn"/, "Four-piece limit modal should expose an explicit apply button.")
assert.match(indexHtml, /id="cancelCalculationConfigBtn"/, "Calculation config modal should expose an explicit cancel button.")

const workbenchIndex = indexHtml.indexOf('id="driveDiscSchemeTabs"')
const resultTabsIndex = indexHtml.indexOf('id="optimizerResultTabs"')
const schemeListIndex = indexHtml.indexOf('id="driveDiscSchemeList"')
assert.ok(workbenchIndex >= 0 && resultTabsIndex > workbenchIndex, "Optimized candidates should be nested in unified scheme tabs.")
assert.ok(schemeListIndex > resultTabsIndex, "Only one active scheme list should render below unified tabs.")

assert.match(calculateJs, /function optimizedSchemes\(\) \{\s*return optimizationResults\.map\(optimizedScheme\)/s)
assert.match(calculateJs, /function schemeTabs\(\) \{\s*return \[\s*manualScheme\(\),\s*loadoutScheme\(\),\s*\.\.\.optimizedSchemes\(\),\s*\]/s)
assert.match(calculateJs, /return Number\.isFinite\(activeMultiplier\) \? activeMultiplier !== 1 : true/, "Missing stored stun state should default to enabled.")
assert.match(calculateJs, /manuallyUncheckedDefaultBuffIds/, "Default combat Buff exclusions should be persisted separately from active ids.")
assert.match(calculateJs, /function optimizerStorePayload\(/, "Optimizer worker payload should be trimmed before structured cloning.")
assert.match(calculateJs, /rawIndex: disc\.source\.rawIndex/, "Optimizer worker payload should keep only lightweight source metadata.")
assert.match(calculateJs, /store: optimizerStore/, "Worker should receive the trimmed optimizer store.")
assert.doesNotMatch(calculateJs, /settings: collectOptimizationSettings\(\),\s*store,/s, "Worker input should not duplicate the full browser store.")
assert.match(calculateJs, /SharedCombat\.runtimeStackGroups\(buff\)/, "Optimizer Buff runtime UI should render stack controls from shared stack groups.")
assert.match(calculateJs, /data-runtime-stack-group/, "Optimizer Buff runtime stack inputs should carry their shared stack group key.")
assert.match(calculateJs, /runtimeStackRuleIdsForGroup/, "Optimizer Buff runtime updates should write one stack value to every grouped rule.")
assert.match(calculateJs, /combatBuffDraftAddedBuffs/, "Combat Buff modal should edit a draft before applying.")
assert.match(calculateJs, /function applyCombatBuffModalSelection\(\)/, "Combat Buff modal should apply draft changes explicitly.")
assert.match(calculateJs, /twoPieceSetDraftIds/, "Two-piece modal should edit draft set limits before applying.")
assert.match(calculateJs, /fourPieceSetDraftId/, "Four-piece modal should edit a draft set limit before applying.")
assert.match(calculateJs, /calculationConfigModalSnapshot/, "Calculation config modal should restore a snapshot when cancelled.")
assert.doesNotMatch(calculateJs, /const candidate = event\.target\.closest\("\[data-candidate-key\]"\)[\s\S]{0,700}closeCombatBuffModal\(\)/, "Clicking a Buff candidate should not immediately close the modal.")
assert.match(calculateJs, /OPTIMIZER_WORKER_STALL_TIMEOUT_MS/, "Optimizer worker should have a no-progress watchdog.")
assert.doesNotMatch(calculateJs, /pendingOptimizationCancelPromise\s*=\s*\(async\s*\(\)\s*=>\s*\{/s, "Cancel cleanup should not be hidden inside a synchronously-resolving async IIFE.")
assert.match(calculateJs, /const cancelPromise = Promise\.resolve\(\)\.then\(\(\) => \{/s, "Cancel promise should be assigned before the cleanup body runs.")
assert.match(calculateJs, /\.finally\(\(\) => \{\s*if \(pendingOptimizationCancelPromise === cancelPromise\) \{\s*pendingOptimizationCancelPromise = null\s*\}/s, "Cancel promise should clear its pending marker after cancellation finishes.")
assert.doesNotMatch(calculateJs, /function allSchemes\(\)/, "Mixed manual/loadout/result scheme tabs should not be reintroduced.")
assert.doesNotMatch(calculateJs, /renderDiscPicker|selectedDiscIdsFromPicker/, "Old select-based manual picker should stay removed.")
